// Generated by CoffeeScript 1.4.0
var Alert, uploader;

uploader = (function() {

  uploader.prototype.options = {
    acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
    url: SYS.baseUrl + "uploader/temp",
    dataType: 'json'
  };

  function uploader(o) {
    $.extend(this, o);
    this.init();
  }

  uploader.prototype.init = function() {
    var _this = this;
    this.selector.fileupload(this.options);
    this.selector.bind('fileuploadadd', function(e, data) {
      $(this).data('fileupload')._trigger('sent', e, data);
      return typeof this.addCallback === "function" ? this.addCallback(e, data) : void 0;
    });
    this.selector.bind('fileuploadprogress', function(e, data) {
      var progress;
      progress = parseInt(data.loaded / data.total * 100, 10);
      return typeof _this.progressCallback === "function" ? _this.progressCallback(progress) : void 0;
    });
    return this.selector.bind('fileuploaddone', function(e, data) {
      return typeof _this.doneCallback === "function" ? _this.doneCallback(e, data) : void 0;
    });
  };

  return uploader;

})();

Alert = (function() {

  function Alert() {}

  Alert.prototype.status = "success";

  Alert.prototype.strong = "Well done!";

  Alert.prototype.message = "";

  Alert.prototype.prepend_selector = $('div.main');

  Alert.prototype.setStatus = function(status) {
    this.status = status;
    switch (status) {
      case "success":
        this.strong = "Исполнено!";
        break;
      case "error":
        this.strong = "Не получится!";
        break;
      case "info":
        this.strong = "Уведомление!";
        break;
      default:
        this.strong = "Уведомление!";
    }
    return this;
  };

  Alert.hideAll = function() {
    return $(".alert").remove();
  };

  Alert.factory = function() {
    return new Alert;
  };

  Alert.prototype.setLayout = function(layout) {
    switch (layout) {
      case "main":
        this.prepend_selector = ".my-container";
        break;
      case "admin":
        this.prepend_selector = ".span8";
    }
    return this;
  };

  Alert.prototype.setMessage = function(message) {
    this.message = message;
    return this;
  };

  Alert.prototype.render = function() {
    var html;
    $(".alert").remove();
    html = "<div class=\"alert alert-" + this.status + "\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\">×</button><strong>" + this.strong + "</strong> " + this.message + "</div>";
    return $(this.prepend_selector).prepend(html);
  };

  return Alert;

})();

$(document).ready(function() {
  var name, name_test, new_sub_test, new_test_form, submit,
    _this = this;
  new_test_form = $('.newTest');
  name = new_test_form.find('.input-medium');
  submit = new_test_form.find('.btn');
  new_test_form.submit(function(e) {
    e.preventDefault();
    submit.attr('disabled', true);
    return new_test_form[0].submit();
  });
  name.keyup(function(e) {
    var name_text;
    name_text = $(e.target).val();
    if (name_text.trim() !== '') {
      return submit.removeAttr('disabled');
    } else {
      return submit.attr('disabled', true);
    }
  });
  new_sub_test = $('.newSubTest');
  name_test = new_sub_test.find('.input-big');
  return name_test.keyup(function(e) {
    var name_test_text, submit_t;
    name_test_text = $(e.target).val();
    submit_t = $(e.target).next('.btn');
    if (name_test_text.trim() !== '') {
      return submit_t.removeAttr('disabled');
    } else {
      return submit_t.attr('disabled', true);
    }
  });
});
