// Generated by CoffeeScript 1.4.0
var Tagit;

Tagit = (function() {

  function Tagit() {
    this._init();
  }

  Tagit.prototype._init = function() {
    this._maskInput();
    this._takeTestInit();
    this._initTagit();
    return this._initZebra();
  };

  Tagit.prototype._initZebra = function() {
    var tr;
    tr = $('.newSubTest').parents('td').parent('tr');
    return tr.find('td').css('background-color', '#fff');
  };

  Tagit.prototype._maskInput = function() {
    return $('input[name="question_count"]').numberMask();
  };

  Tagit.prototype._takeTestInit = function() {
    return $('.take').click(function(e) {
      var form;
      e.preventDefault();
      $.cookie('test', 'juihmefdjs5dvg94d1toa1abl5');
      form = $(this).parent('form');
      if ($(this).is('.generate')) {
        form.children('input[name="take"]').val(0);
      } else {
        form.children('input[name="take"]').val(1);
      }
      return form.submit();
    });
  };

  Tagit.prototype._initTagit = function() {
    var _this = this;
    return $('.categories-select').tagit({
      removeConfirmation: true,
      allowSpaces: true,
      tagSource: function(req, response) {
        return $.ajax({
          url: SYS.baseUrl + 'admin/tests/get_type_category',
          data: {
            term: req.term
          },
          type: 'POST',
          dataType: "json",
          success: function(data) {
            return response($.map(data.data, function(item) {
              return {
                label: item.value
              };
            }));
          }
        });
      },
      afterTagAdded: function(event, ui) {
        if ($(ui.tag).is('.old')) {
          return false;
        }
        return _this._actionType($(ui.tag), 'added')();
      },
      beforeTagRemoved: function(event, ui) {
        if ($(ui.tag).is('.general')) {
          return false;
        }
        if (confirm('Удалить категорию?')) {
          return _this._actionType($(ui.tag), 'remove')();
        } else {
          return false;
        }
      }
    });
  };

  Tagit.prototype._actionType = function(el, action) {
    var category, level, name;
    name = el.find('.tagit-label').html();
    category = el.parents('table').data('category');
    level = el.parents('tr').data('level');
    el.addClass('old');
    return $.ajax({
      url: SYS.baseUrl + 'admin/tests/ajaxActionType',
      data: {
        name: name,
        category: category,
        level: level,
        action: action
      },
      type: 'POST',
      dataType: 'json'
    });
  };

  return Tagit;

})();

$(document).ready(function() {
  return new Tagit;
});
